### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by teozkr** [BlocklandGlass/BlocklandGlass#10]
Like RTB: There should be some way to specify preferences that the admin can set through a unified API.

**Comment by teozkr** [comment]
Could be either declared programmatically or in the `glass.json` manifest. The former would mean less work for an eventual shim (should this be provided?), the latter would be easier to present visually when the add-on is disabled. @Jincux thoughts?

**Comment by Jincux** [comment]
I believe we agreed that it will be picked up with the new parser, right?

Also, just wanted to note: backwards compatibility with RTB prefs.

**Comment by teozkr** [comment]
Right, made that comment before we had that discussion.
