### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by teozkr** [BlocklandGlass/BlocklandGlass#11]
When server-side functionality (such as #10) will start being added there needs to be a decision on how to decide who should have access to what. To me the following options seem viable:

1. Hard-code everything to require either admin or super-admin, like RTB
2. Expose a more flexible API (like Server_Permissions), but provide a default implementation that behaves like the above
3. The above, but actually rewrite and bundle something resembling Server_Permissions

To me option 2 seems the most viable in the short term. It solves the problem quickly, but leaves the door open to migrate to more sophisticated solutions later on, possibly even as a separate add-on.

**Comment by Jincux** [comment]
For simplicity sake, I think an initial version should just be based around admin and super-admin. From there, it can be expanded in to a more complex, optional system.
