### ISSUE TITLE
Better Support_Updater interface support

### ISSUE THREAD

**Issue by Greek2me** [BlocklandGlass/BlocklandGlass#12]
Support_Updater already has support for third-party interfaces (admittedly undocumented). Instead of the hacky method you're using to replace the Support_Updater GUI, just use its built-in interface hooks:

	updaterInterfacePushItem(%item) //Called when an item is added to the display.
	updaterInterfacePopItem(%item) //Called when an item is removed from the display.
	updaterInterfaceSelectItem(%item) //Called when the updater selects an item to display in detail (changelog, etc).
	updaterInterfaceOnQueueEmpty() //Called when the queue is empty.
	updaterInterfaceDisplay(%refreshing) //Called when updates are ready to be displayed to the user.

Where %item above is an UpdaterAddOnSO object:

	==>updater.queue.getObject(0).dump();
	Member Fields:
	  class = "UpdaterAddOnSO"
	Tagged Fields:
	  channel = "release"
	  guiSwatch = "15393"
	  name = "Gamemode_Slayer_Territory"
	  repository0 = "13741"
	  repositoryCount = "1"
	  repositoryIdx13741 = "0"
	  updateFile = "mods.greek2me.us/storage/Gamemode_Slayer_Territory/Gamemode_Slayer_Territory.zip"
	  updateVersion = "1.0.0+20140525"
	  version = "0.5.0"
	Methods:
	  addRepository() - 
	  call() - 
	  delete() - obj.delete()
	  dump() - obj.dump()
	  getClassName() - obj.getClassName()
	  getGroup() - obj.getGroup()
	  getId() - obj.getId()
	  getModID() - 
	  getName() - obj.getName()
	  getTaggedField() - obj.getTaggedFieldCount(int idx)
	  getType() - obj.getType()
	  hasRepository() - 
	  save() - obj.save(fileName, <selectedOnly>)
	  schedule() - object.schedule(time, command, <arg1...argN>);
	  scheduleNoQuota() - object.schedule(time, command, <arg1...argN>);
	  setName() - obj.setName(newName)
	==>
	==>
	==>
	==>
	==>
	==>
	==>updater.queue.getObject(0).repository0.dump();
	Member Fields:
	  class = "UpdaterRepoSO"
	Tagged Fields:
	  cacheFile = "config/common/updater/cache/bfe4e745cdf7a5d1b3d86984397100d50bf843c1.txt"
	  fallbackCount = "0"
	  format = "TML"
	  hash = "bfe4e745cdf7a5d1b3d86984397100d50bf843c1"
	  isFallback = "0"
	  queried = "1"
	  tcp = "15357"
	  url = "mods.greek2me.us"
	Methods:
	  _parseJSON() - 
	  addFallback() - 
	  call() - 
	  delete() - obj.delete()
	  dump() - obj.dump()
	  getClassName() - obj.getClassName()
	  getGroup() - obj.getGroup()
	  getId() - obj.getId()
	  getName() - obj.getName()
	  getTaggedField() - obj.getTaggedFieldCount(int idx)
	  getType() - obj.getType()
	  parseLocal() - 
	  queryRemote() - 
	  save() - obj.save(fileName, <selectedOnly>)
	  schedule() - object.schedule(time, command, <arg1...argN>);
	  scheduleNoQuota() - object.schedule(time, command, <arg1...argN>);
	  setName() - obj.setName(newName)

**Comment by Jincux** [comment]
Is there any in-built way to override the default interface, or should I continue to just keep the gui from being pushed by packaging ```canvas::pushDialog()```?

**Comment by Greek2me** [comment]
Yes, just overwrite the functions listed above! That's exactly what they're for.

**Comment by Greek2me** [comment]
Hm, I just looked at your commit. These are callbacks - you shouldn't need to call them.

**Comment by Greek2me** [comment]
It looks like you are breaking the updater queue by adding them to the GlassUpdatesGroup group.

**Comment by Jincux** [comment]
It shouldn't be

```
%up = new ScriptObject() {
    class = "GlassUpdate";
    addonHandler = %item;
  };

  GlassUpdatesGroup.add(%up);
```

I made sure not to add the item to a group by just making a proxy object instead.

**Comment by Jincux** [comment]
Out of the callbacks, I don't see how I could use anything other than ```updaterInterfacePushItem(%item)``` and ```updaterInterfaceDisplay(%refreshing)```. The rest of the interactions require directly interfacing with the updater queue or are self-contained within the scope of the gui.

**Comment by Greek2me** [comment]
Ah, ok. I misread that then. I'm on mobile.

updaterInterfaceSelectItem is used when the updater goes to the next download. The standard updater interface uses this to display information about the file as it's being downloaded (change log, etc.). The updaterInterfacePopItem is used to remove the completed item from the GUI.
