### ISSUE TITLE
Server Preferences - RTB/Glass Prefs Synchronization

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#126]
this is mainly a Support_Preferences issue, but I am logging it down here so I/we don't forget about it.

when having both Glass and RTB _on a server_, the preferences don't synchronize between each other when they are changed in either.

on a client, Glass and RTB are fine to have so there's no issues regarding that.

**Comment by Jincux** [comment]
alternatively could overwrite RTB and have Support_Preferences be responsible for updating the RTB gui
