### ISSUE TITLE
Mod Manager page navigation broken

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#141]
opening the second page in the Blockland Glass mod manager will open a non existent add-on(?, not sure if this is a page considering it says "No Add - Ons found") named whatever board ID you're browsing (For example, opening any other page on https://blocklandglass.com/addons/board.php?id=12 will open the addon 12) will open up

this doesn't seem to apply to the first page

**Comment by Jincux** [comment]
Likely due to Crown's recent URL changes
