### ISSUE TITLE
String buffer memory collisions?

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#146]
**pls fix mod manager i posted too many bugs in one day**

anyway yadda yadda yadda glass mod manager is loading a part of description from another addon by the same author (queuenard)

here is image: http://imgur.com/cJyJDCC

more info: here is the addons description which is what its supposed to be: https://blocklandglass.com/addons/addon.php?id=483 (the description too long) and at sentence "Because the isometric images are produced at different zoom levels" it gets cut and at "different zoom levels" and loads part of another description of an addon which is here: https://blocklandglass.com/addons/addon.php?id=505

also i don't know if this matters or not but before it used to spew out random numbers and now its displaying other addon descriptions

**Comment by Jincux** [comment]
Seems to be an issue with `getUTF8String()`, input is too long. Engine issue leads to string collisions.
