### ISSUE TITLE
Text limit for Mod Manager too low

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#147]
Anyway earlier today I posted a bug about the descriptions being butchered, and when that was fixed I guess it showed another bug?

So if you open https://blocklandglass.com/addons/addon.php?id=483 (how can this addon cause more than 2 issues alone) the text limit is too small, making "accordingly." being cut off.

This isn't a huge bug, although if future mods were to have big descriptions it would be very hard to read without opening the website.

Image: http://imgur.com/HKZDLte

**Comment by Jincux** [comment]
Last word was clipped, fixed.
