### ISSUE TITLE
"Enable All", "Defaults", and "Disable All" have a big gap.

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#148]
Going to Overlay > Mod Manager > My Add - Ons there's a huge gap between "Defaults", "Enable All", "Disable All" and "Apply". I'm not sure if this is set for an add-on logo or for addon previews.

Image: http://imgur.com/95xgRCb

**Comment by Jincux** [comment]
There's just nothing else to put there

**Comment by qu47** [comment]
then put it in middle ;((((((((
