### ISSUE TITLE
Add colorset logo on colorset items where the images would usually be.

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#149]
Most Add - On's have an image attached to them, and it doesn't seem that Colorsets have an image attached to them 99% of the time. So we can utilize this image space by adding the Colorset logo inside it.

### Image
![colorset](https://cloud.githubusercontent.com/assets/25020307/21868544/dc900352-d818-11e6-963a-ebfd134b8906.PNG)
**Space inside Red Circle** -- _This is where the image(s) would normally be, and inside that space you could add the colorset logo. (oh also it circled some text pls ignore that i cant draw with mouse 😭 also this emoji looks dumb)_

**Comment by Jincux** [comment]
This is done automatically for any new colorsets and is the responsibility of the add-on author to do for previous colorsets. Also, the term you're looking for is image or screenshot, not logo.

**Comment by qu47** [comment]
fixed even tho its closed
