### ISSUE TITLE
Avatar preview in Friends List has incorrect face texture

### ISSUE THREAD

**Issue by Ipquarx** [BlocklandGlass/BlocklandGlass#151]
Not sure what's causing this, just reporting it as I see it.

Face texture in friends list:

![](http://i.imgur.com/idq0A3Z.png)

Face texture on actual avatar:

![](http://i.imgur.com/xvudwGJ.png)

**Comment by Jincux** [comment]
What's the value of `$Pref::Avatar::FaceName` ?
