### ISSUE TITLE
Joining Players on Glass not working.

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#152]
rlcbm was constantly bugging me to join his server and I wanted to try and use Glass' new feature of joining/inviting servers. However, this seems to be broken if the other person is hosting a server. It says "Would you like to join the server **rlcbm** is on?" when I click the "Join" button, and when I click "**YES**" it proceeds with the message "**rlcbm** is not currently playing on a joinable server."

rlcbm is using 4.0.0 and so is the server so I don't see what's wrong.

### Images
![rlcbm](https://cloud.githubusercontent.com/assets/25020307/21868262/a6f0dd08-d817-11e6-935a-d47a7525ca3e.PNG)
_rlcbm's userpage_

![Server](https://cloud.githubusercontent.com/assets/25020307/21868270/b0a9db92-d817-11e6-8c62-0c93d681fb19.PNG)
_The server listed on Blockland's master list._

![Box](https://cloud.githubusercontent.com/assets/25020307/21868308/da0ae49a-d817-11e6-9b3e-78941c7be1c3.PNG)
_Message Box 1_

![Box](https://cloud.githubusercontent.com/assets/25020307/21868305/d31cb776-d817-11e6-8c46-02cb02d3d73d.PNG)
_Message Box 2_

**Comment by Paperworx** [comment]
this appears to occur with servers where the glass user is hosting -- the host doesn't appear to update their location data.

**Comment by qu47** [comment]
how can the host manually update their location data
