### ISSUE TITLE
'My Colorsets' Highlight Swatch in front of icons?

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#155]
the 'My Colorsets' highlight swatch on the colorset swatches appears to be on top of the icons (this may also be stopping the Glass colorset icon from functioning properly ie being able to click it and take the user to the Glass add-on page for the colorset).

**ideally, the highlight swatch should be removed (on the colorset swatches) as the 'My Add-Ons' page does not utilize them either.**

**Comment by qu47** [comment]
yes a feature to make the mod manager looks good just because you cant fix one thing should be removed

_round of applause_
