### ISSUE TITLE
* at end of "Glass Loading Gui" has no use

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#159]
You could easily make this have a use by adding an * to the start of "**Requires restart.**" in the information for the setting.

### Images
![Setting](https://cloud.githubusercontent.com/assets/25020307/21872108/34568d82-d82c-11e6-9599-93f953abb51e.PNG)
_The setting in it's natural habitat._

![Box](https://cloud.githubusercontent.com/assets/25020307/21872123/62a8170a-d82c-11e6-8d71-0241312e24d7.PNG)
_Oh no! A wild message box!_

Also if this is possible you could remove the * for the title bar on the information window.

**Comment by Jincux** [comment]
It denotes that reading the description is important and that there's more to know. This is common between all legal texts or advertising material or just generally in most of the developed work
