### ISSUE TITLE
Live - Blank "message" being sent from friend

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#161]
Got a blank message from my friend before he shortly joined a server. He never actually sent a message or anything, but it seems like it was supposed to display a server join message? I couldn't take a picture of it in time though.

**EDIT** -- It seems to be reproducible. Asked my friend to reopen Blockland, and it happens when 
he reopens Blockland. Same goes for joining/reconnecting to Glass. 
This also seems to happen for everyone.

### Images

![](https://i.imgur.com/6xjtC8r.png)
![granddad](https://cloud.githubusercontent.com/assets/25020307/21912574/63ddea58-d8ec-11e6-94f3-c9be37be6366.PNG)

**Comment by Jincux** [comment]
Please post a way to reproduce the issue

**Comment by qu47** [comment]
I don't know how to reproduce it, it came out of no where.

**Comment by qu47** [comment]
This happened again to me.

**Comment by Jincux** [comment]
Can't reproduce, open again if persists
