### ISSUE TITLE
Not able to download Add - On ingame.

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#162]
Offending Add - On:

https://blocklandglass.com/addons/addon.php?id=415

### GIF

![aa](https://cloud.githubusercontent.com/assets/25020307/21872864/8d4676ba-d830-11e6-9f3b-0160faa8c8f8.gif)
_Downloading it again and again although it won't download._

**EDIT** -- It seems this only happens on this add-on. It won't download on the website nor on client.

**Comment by Jincux** [comment]
Need console.log
