### ISSUE TITLE
When Alt + Tabbing, Glass Stops working.

### ISSUE THREAD

**Issue by gustarrini** [BlocklandGlass/BlocklandGlass#167]
When you alt tab to check something and goes back to blockland, it just doesnt opens the glass menu anymore, however, noftications still works fine.

i don't know if it's a known bug, just leaving it here.

**Comment by Paperworx** [comment]
this is not a glass issue, your keybind isn't working because windows/blockland is detecting that your ctrl key is depressed when it isn't.

press your ctrl key after you alt + tab and it should work, if it doesn't then try all the other special keys.
