### ISSUE TITLE
Friend being online yet displayed as offline & more in issue desc

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#172]
**TITLE CONTINUED** --  "_Friend being online yet displayed as offline, and avatar is black (even though running 4.0.0)_"

### Images
![gost](https://cloud.githubusercontent.com/assets/25020307/21910596/59a3b55e-d8e2-11e6-8fd1-0b07f4889068.PNG)
_Must be a ghost running Shock. I assume Jincux is also Obama and Shock is Joe Biden._

![shockisded](https://cloud.githubusercontent.com/assets/25020307/21910619/6ca09e60-d8e2-11e6-82e5-fba26c0780be.PNG)
_On second thought, maybe it's the NSA._

**Comment by Jincux** [comment]
Please include methods to reproduce in future reports. There's nothing we can do if we can't reproduce the issue.
