### ISSUE TITLE
Custom LoadingGui produces errors

### ISSUE THREAD

**Issue by ClayHanson** [BlocklandGlass/BlocklandGlass#192]
It seems like Jincux deletes the actual LoadingGui gui and replaced it with his custom one. This produces errors for users with mouse scrolling. The error is "Unable to find object: 'LoadingGui', attempting to call 'isAwake'". The error is produced from the default game scripts.

**Comment by ClayHanson** [comment]
Also, forgot to put this down, but a possible solution is just doing 'new GuiControl(LoadingGui){};' or just naming your custom gui to 'LoadingGui'

**Comment by ClayHanson** [comment]
Okay, update: This bug actually makes it seem that you cannot connect to servers sometimes. I connected to Crown's server, and the loading gui did not show up at all, so I thought Crown's server crashed. Then, I opened up the console and found out that I was actually loading

**Comment by Jincux** [comment]
The LoadingGui is deleted and replaced with another object named LoadingGui which is identical to the original. If there's no object named LoadingGui, that's not Glass's fault

**Comment by Jincux** [comment]
Changed loadinggui method, shouldn't happen anyway
