### ISSUE TITLE
Website - Incorrectly categorized add-ons

### ISSUE THREAD

**Issue by paperworx** [BlocklandGlass/BlocklandGlass#195]
~~someone approved [this add-on](https://blocklandglass.com/addons/addon.php?id=556) into the wrong category.~~

see comment.

**Comment by Paperworx** [comment]
@Jincux 

- [ ] **Gamemode_Slayer should be re-categorized from Server Mods to Gamemodes.**
- [ ] Weapon_DSmileyBall should be re-categorized from Decals to Weapons.
- [ ] Item_MSMegaphone should be re-categorized from Items to Novelty.
- [ ] Item_You_Tried should be re-categorized from Items to Novelty.
- [ ] Client_Jailbreak should be re-categorized from Client Mods to Clients.
- [ ] Item_Powerup should be re-categorized from Server Mods to Items.
- [ ] Item_ArmorPickup should be re-categorized from Server Mods to Items.
- [ ] Script_TotalRPG should be re-categorized from Server Mods to Events.
- [ ] Light_Dark should be re-categorized from Bricks to Lights.
