### ISSUE TITLE
Website - Reduce download counter rigging

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#201]
cache downloaders' IPs to memory temporarily: if IP in memory, don't increase download counter.
does not need use of a database.

**Comment by Draaked** [comment]
What, you don't think this is legit?
![image](https://cloud.githubusercontent.com/assets/23016589/22186208/e72cf2de-e0bf-11e6-8024-7bee3ff0ada6.png)
