### ISSUE TITLE
Updater repo uses incorrect tags

### ISSUE THREAD

**Issue by Greek2me** [BlocklandGlass/BlocklandGlass#21]
The update repository uses the invalid tag, "restart". This should be "restartRequired".

current output:

	{
		"name": "Blockland Glass Generated Repo",
		"add-ons": [

			{
				"name": "System_BlocklandGlass",
				"description": "Blockland Glass has had a very on-off history over the past five years, popping up many times as entirely separate projects- that never really got used.<br><br>Now it's back, and this time it's here to stay. Glass is starting off with a mod manager. Obviously, you're here and you can see it. There's much more planned down the road, but I hope you like it as it is for now.<br><br>__You can find up-to-date development topics on the forums!__",
				"channels": [
					{
						"name": "stable",
						"version": "1.0.1",
						"restart": "1.0.1",
						"file": "http://api.blocklandglass.com/api/support_updater/download.php?id=11&branch=1",
						"changelog": "http://api.blocklandglass.com/api/support_updater/changelog.php?id=11&branch=1"
					},
					{
						"name": "development",
						"version": "1.0.1-alpha.1",
						"restart": "1.0.1-alpha.1",
						"file": "http://api.blocklandglass.com/api/support_updater/download.php?id=11&branch=3",
						"changelog": "http://api.blocklandglass.com/api/support_updater/changelog.php?id=11&branch=3"
					}
				]
			}
		]
	}

**Comment by Jincux** [comment]
fixed
