### ISSUE TITLE
Can't update submodules through Git Shell

### ISSUE THREAD

**Issue by gustarrini** [BlocklandGlass/BlocklandGlass#213]
i'm just gonna leave this here
![image](https://cloud.githubusercontent.com/assets/18196173/22423624/a15b3052-e6d9-11e6-99aa-19d7a00f94b9.png)

**Comment by Jincux** [comment]
This has to do with git and possibly your configuration. The submodule system is pretty standard and we don't do anything complicated that would cause an issue.
