### ISSUE TITLE
Add-on List not Alphabetized

### ISSUE THREAD

**Issue by JoshuaBrockschmidt** [BlocklandGlass/BlocklandGlass#244]
When running Blockland through Wine on Ubuntu, the add-on list is not alphabetized ![See picture for reference](https://cloud.githubusercontent.com/assets/10371153/26023820/a5376218-3779-11e7-98fc-cb83b811536e.png). A similar problem is encountered when loading the add-on list for a Custom game while running Blockland through Wine. [See this forum post for context](https://forum.blockland.us/index.php?topic=309694.15). Apparently, something about Linux file system (presumably something to do with Ext4) loads files in an unalphebetized order, while Windows and Mac load files alphabetically by design. Likewise, I assume this is only an issue encountered on Linux. Nonetheless, a Q-sort of the add-on list should do the trick.

**Comment by Jincux** [comment]
As this is an engine-wide issue, it's not really in our scope to address. You can fix the issue by having a separate NFTS parition.
