### ISSUE TITLE
Glass Graphs - mRound + Animation Spam

### ISSUE THREAD

**Issue by ClayHanson** [BlocklandGlass/BlocklandGlass#246]
I'm getting a bunch of errors after I open the Blockland Glass Prefs' graphs tab. It's trying to call a non-existent function (mRound) while it does its animation. The actual function's name is round();. Also, it seems like when I close the prefs window, it still does the animation a bunch of times (it keeps echoing 'anim done' in the console).

**Comment by Paperworx** [comment]
non-existent function fixed in 95c0866
