### ISSUE TITLE
Remove the e-mail client verification

### ISSUE THREAD

**Issue by McTwist** [BlocklandGlass/BlocklandGlass#249]
The e-mails is sent from the server when authenticating. The problem that is raised is that they can now easily be retrieved and used to go around the authentication process. Having Blockland Authentication server as a requirement is not an excuse, as mentioned in #248.

That is, remove the client verification and rely on the server.

**Comment by McTwist** [comment]
Due to the new DAA system, this will be fixed in 4.2.

**Comment by Jincux** [comment]
Done in 23e09a8
