### ISSUE TITLE
Preferences - Colorset type does not show up in GUI

### ISSUE THREAD

**Issue by jcbrockschmidt** [BlocklandGlass/BlocklandGlass#258]
For example, when I run

`registerPref("Test", "General", "Test Color", "colorset", "$testColor", "Script_TestColor", 2, "", "", 0, 0, 0);`

Nothing shows up in the Glass Server Preferences GUI. However, when I execute `echo($testColor)`, I still get the number 2. Likewise, when I run `TestPrefs.getCount()`, I get 1, indicating that a preference has indeed been registered. Furthermore, I know _colorset_ is a valid type, as can be clearly seen in the code for [Support_Preferences](https://github.com/TheBlackParrot/blockland-preferences/blob/master/server.cs#L138). Hence, I can only conclude that this is a problem with Blockland Glass.

Also, do note that the code I posted serves as a simplified example, and was hence not actually executed in-game. The code I actually ran was

`registerPref("Better Trench Tool", "Color", "Default Dirt Color", "colorset", "$BTT::defaultColor", "Tool_BetterTrenchTool", 0, "", "", 0, 0, 0);`

I was also able to confirm that this actually created the corresponding Preference object and global variable.

**Comment by Jincux** [comment]
It may be that the preference type was never implemented on Glass's behalf despite being in the Support_Preferences specification. I'll take a look and try to ship it (or a fix) with 4.2
