### ISSUE TITLE
Server Preview - No playerlist when special character in name

### ISSUE THREAD

**Issue by Draaked** [BlocklandGlass/BlocklandGlass#259]
If there is a player with a special character in their name the playerlist does not load. The same thing happens on the website, must be something wrong with how its sent.

**Comment by McTwist** [comment]
Sounds like a charset issue. Either ban such characters or try to do an encoding conversion.

**Comment by Jincux** [comment]
probably a JSON encode/decode issue, the PHP `json_decode` and `json_encode` methods just return false if handed a character they don't like.

**Comment by 31547** [comment]
what do you mean by "special character"? do you mean a character outside of windows-1252/latin-1, or do you mean a character outside of utf-8?

@Jincux 
how does the client communicate with the api? what api does it communicate with for this?

**Comment by Jincux** [comment]
Any non-ascii character. The character exists in both character sets, just under different encoding.

This has already been resolved.
