### ISSUE TITLE
The fonts are broken.

### ISSUE THREAD

**Issue by Lykaksparsz** [BlocklandGlass/BlocklandGlass#260]
![blockland_2017-12-24_17-53-36](https://user-images.githubusercontent.com/16814584/34327685-9461b4a0-e8d3-11e7-92a9-61c5174420a9.png)
I cannot see messages and text...
Please fix this!

**Comment by McTwist** [comment]
What OS are you using?

**Comment by Lykaksparsz** [comment]
@McTwist Windows 7 64-bit
