### ISSUE TITLE
Live - Private Server Location Issue With Friends

### ISSUE THREAD

**Issue by Draaked** [BlocklandGlass/BlocklandGlass#262]
When a player has their location set to private, their friends are still able to see their location until opening their "Glass User" page. After that, it changes to "Location Private" as expected.

**Comment by 31547** [comment]
where is the location fetched from on the glass client for the friends view versus user page? if the location is fetched from the same data source for both, then the ui somehow has to update on request from the server or somehow figure out when the change happens.  perhaps the ui is unable to update until the window is reopened.  i will look for data sources when i figure out the codebase

**Comment by 31547** [comment]
`GlassFriendsGui_StatusSelect::updateStatus();` should have the same data source as the page for viewing a user-- i found this by looking at `/client/gui/GlassFriendsGui.gui` at line 131

**Comment by 31547** [comment]
[https://github.com/BlocklandGlass/BlocklandGlass/blob/master/client/submodules/live/GlassLiveUser.cs](url)

the relevant code is at line 244

**Comment by 31547** [comment]
[https://github.com/BlocklandGlass/BlocklandGlass/blob/2637def9659ebd7069fa29f50c3ccec3bd9b9021/client/submodules/live/GlassLiveConnection.cs]()

[https://github.com/BlocklandGlass/BlocklandGlass/blob/2637def9659ebd7069fa29f50c3ccec3bd9b9021/client/GlassLive.cs]()

relevant parts of the codebase ^

line 602.  `//this is only in response to getLocation` 

`getLocation` should be called whenever the friends list is opened up with a check on the data source for if they're private or not.  or, the client should just interpret the data as being `private`.  `getLocation` in some form isn't being called on the friends list as it should.

**Comment by LakeYS** [comment]
Closing, stale + won't be relevant with the upcoming changes.
