### ISSUE TITLE
Some users are authenticating as other users

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#30]
Every once in a while, a user joins Glass Chat and realizes that their name isn't who they actually are.
This is a major issue which needs to be looked into, the problem is that it's hard to figure out why it's happening.

It's especially worrying when such a user suffering from this issue can happen to become a user who has moderator privileges (accidental impersonation of a staff user).

Some notes:

* A user who suffers from this issue seems to always have the issue (pretty much ruining their Glass Chat experience and prompting them to remove Glass), and a user who doesn't ever have this issue never comes up with it.

* Every time the user suffering from the issue reconnects to Glass Chat, their name will change to someone elses most of the time.

* ~~Users suffering from this issue report that Glass Live displays their real information correctly - but Glass Chat is the one that always misidentifies them.~~ Players are authing as other people and even accessing their friends lists, see https://github.com/BlocklandGlass/BlocklandGlass/issues/30#issuecomment-252879459

I think this has something to do with the server auth/cache side, not with the Glass Client itself.

![Issue Example](https://i.gyazo.com/66d20ec085aa05d06296f39b14162408.png)

**Comment by Paperworx** [comment]
Just happened to me:

[![Video](https://img.youtube.com/vi/do4xbe07ZSg/0.jpg)](https://www.youtube.com/watch?v=do4xbe07ZSg)

**Comment by Jincux** [comment]
Just thinking aloud, likely an issue with variable scope during authentication and multiple users authenticating at once. Also likely issue with special characters, some part of the authentication system doesn't handle them well

**Comment by Jincux** [comment]
Could be related to special characters causing auth failures/hangs leading to issues with async login due to poor variable management.
