### ISSUE TITLE
Brick_LShaped Repo/version.json Mismatch

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#53]
The latest version of Brick_LShaped's version.json has its version number set at 0, but the repo reports Brick_LShaped is version 5.

This leads to Brick_LShaped reporting that it needs to update every time Support_Updater checks for add-on updates.

**Solution: Change Brick_LShaped's version.json version number from 0 to 5.**

Investigate how it occurred in the first place, my theory is that the author updated the add-on with the version.json already attached with the version number not set to the actual version number (0 instead of 5).

If the above theory is correct, just make it so updating an add-on forces the replacement of the glass.json/version.json files no matter what.

Maybe find a way to check for add-ons on Glass that don't match their repo version as well so we can amend them.

**Comment by Jincux** [comment]
Likely occurred when site was still having update issues that have since been fixed. The easiest fix is to have the author update the file again, which would inject a correct version.json
