### ISSUE TITLE
Amend SemVer Specification - Add-On Upload

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#56]
> How do I know when to release 1.0.0?
> 
> **If your software is being used in production, it should probably already be 1.0.0**. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

_Source: http://semver.org/#how-do-i-know-when-to-release-100_

Add-ons that are uploaded should be set at version 1.0.0 initially as it denotes that the add-on is ready for public release, below 1.0.0 implies that the add-on _is not_ ready for public release.

It would be a logistical nightmare to suddenly change many add-ons version numbers which are on 0.0.0 to 1.0.0, so simply set all future add-ons uploaded to be at 1.0.0 instead.

**Comment by Jincux** [comment]
This is actually a lot more work than it seems. Planning on taking a pass on upload/file management system, will address then
