### ISSUE TITLE
Website - Invalid uploaded add-on file names

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#72]
Offending add-ons:
- https://blocklandglass.com/addons/addon.php?id=361
- https://blocklandglass.com/addons/addon.php?id=355

They were approved but the file names make them unusable unless renamed manually, they should either be failed so they can be reuploaded by the original author or we can do some script stuff to rename the files in 3.2.0 (I don't really like this idea, but it's an alternative).

I'm also not sure if there are any other add-ons that managed to get approved with invalid file names.

**Comment by Jincux** [comment]
I'm not sure if these were uploaded with these names or this is a result of the database issue with filenames a few weeks ago

**Comment by Jincux** [comment]
New upload system should prevent this
