### ISSUE TITLE
Crash on Preference update

### ISSUE THREAD

**Issue by McTwist** [BlocklandGlass/BlocklandGlass#87]
When trying to update your preferences through the supplied GUI, it always crashes on non-dedicated servers. Calling the server command /UpdatePref manually does not trigger this.

In a trace, I caught it calling `GlassPrefGroup::sendChangedPrefs` as it should do and also went through `glassMessageBoxOk` without any problems, but right before it tried to leave `GlassPrefGroup::sendChangedPrefs` it stopped outputting anything to the log.

I assumed there could be an invalid value here, but as it does not trace `serverCmdUpdatePref`, then it sure is an odd crash and could relate to how Blockland Glass handles it.

**Comment by Paperworx** [comment]
Try removing `Support_Preferences` and re-downloading [Blockland Glass](https://blocklandglass.com/dl.php).
If that does not fix the issue, provide a `console.log`

**Comment by McTwist** [comment]
Here is the log you requested. As I stated, I added a trace before clicking the button.
[console.zip](https://github.com/BlocklandGlass/BlocklandGlass/files/611677/console.zip)

**Comment by Paperworx** [comment]
If you run with default add-ons and Blockland Glass, does it still crash?

**Comment by Jincux** [comment]
There shouldn't be anything causing a crash if it gets to the message box. The loops have already completed at that point.

Support_Preferences deals with the server side of things, however the log doesn't show that it even gets to that point.

**Comment by McTwist** [comment]
I disabled all add-ons but Blockland Glass. I may remove all client add-ons that may have loaded as well if you think that could be an issue as well.

**Comment by Jincux** [comment]
if you rewrite the message box function, just `function glassMessageBoxOk() {}`, does the problem still happen? Torque can have some odd gui quirks.

**Comment by McTwist** [comment]
That seems the case. I tested it and it worked as it should do. Thing is, when I called that function manually from main menu, it worked fine.

**Comment by Jincux** [comment]
In that case, the messageBoxOk dialog is already open but perhaps hidden behind the PlayGui, so changing the profile causes a crash
