### ISSUE TITLE
Disappearing User(s)?

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#95]
![mysterious user](https://i.gyazo.com/039d99b6521c5323c1920de52d0cf5ba.png)

Crown was at the top of the user list and then just disappeared from his spot, I've seen this happen twice now and it always appears to be the very top user only (v3.2.1)

**Comment by Jincux** [comment]
Did this happen randomly or after going offline?

**Comment by Paperworx** [comment]
I believe it happened after he disconnected around 25 minutes ago, yeah.
